### ISSUE TITLE
feature request: ignore JavaScript exceptions if possible, especially for common analytics scripts

### ISSUE THREAD

**Issue by jspraul** [webrecorder/wombat#84]
Often JavaScript-heavy pages don't load correctly if their analytics are not blocked 'cleanly'.

Example with Sentry error: https://web.archive.org/web/20220428144455/https://meet.copilot.com/closing/
```
Uncaught t: Invalid Dsn
    at new t (https://web.archive.org/web/20220428144455js_/https://meet.copilot.com/App/dist/v-637848646487874224/main.js:37:2882)
    at e._fromString (https://web.archive.org/web/20220428144455js_/https://meet.copilot.com/App/dist/v-637848646487874224/main.js:37:3464)
    at new e (https://web.archive.org/web/20220428144455js_/https://meet.copilot.com/App/dist/v-637848646487874224/main.js:37:3138)
    at new e (https://web.archive.org/web/20220428144455js_/https://meet.copilot.com/App/dist/v-637848646487874224/main.js:37:34963)
    at t.e (https://web.archive.org/web/20220428144455js_/https://meet.copilot.com/App/dist/v-637848646487874224/main.js:37:52911)
    at Function.apply (https://web.archive.org/_static/js/wombat.js?v=UHAOicsW:21:60016)
    at new t (https://web.archive.org/web/20220428144455js_/https://meet.copilot.com/App/dist/v-637848646487874224/main.js:37:54450)
    at t._setupTransport (https://web.archive.org/web/20220428144455js_/https://meet.copilot.com/App/dist/v-637848646487874224/main.js:37:57258)
    at t.e (https://web.archive.org/web/20220428144455js_/https://meet.copilot.com/App/dist/v-637848646487874224/main.js:37:43575)
    at Function.apply (https://web.archive.org/_static/js/wombat.js?v=UHAOicsW:21:60016)
```

I am requesting that archived pages continue to load after JavaScript crashes whenever possible. It may not be possible to ignore every error, but it may still be worth implementing specific workarounds for popular analytics scripts.

(In this case I eventually found I could set a breakpoint on `this._options.dsn` and null it out to get things to work.)

**Comment by ikreymer** [comment]
This is a bit tricky since don't really know the source of the error.. Often, it is due to some other rewriting issue, somewhere...

Interestingly, this issue does not occur when using pywb rewriting with passthrough to IA's wayback data, for example:

1) install pywb
2) create `config.yaml` containing:
```
collections:
    ia: cdx+http://web.archive.org/cdx /web
```
3) run pywb, load: http://localhost:8080/ia/20220428144455/https://meet.copilot.com/closing/ and the page loads.

Perhaps @vbanos or @ibnesayeed may be able to look at this further if there's a rewriting issue in IA's wayback that could fix this..

**Comment by ikreymer** [comment]
Closing, as likely not a pywb error.
